services:
  postgres:
    image: postgres:16-alpine
    container_name: shorturl-db
    environment:
      POSTGRES_USER: shorturl
      POSTGRES_PASSWORD: shorturl
      POSTGRES_DB: shorturl
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - cbpt-net

  # backend:
  #   # Descomenta las líneas para usar imagen de Docker Hub:
  #   image: roldyoran/cubepath-shorturl-backend:latest
  #   pull_policy: always

  #   # Construcción local (comenta esto en producción):
  #   #build:
  #   #  context: ./backend
  #   #  dockerfile: Dockerfile

  #   container_name: cbpt-back
  #   env_file:
  #     - .env
  #   environment:
  #     DATABASE_URL: postgres://shorturl:shorturl@postgres:5432/shorturl
  #     API_PORT: ${API_PORT}
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   ports:
  #     - "5044:5044"
  #   restart: unless-stopped
  #   networks:
  #     - cbpt-net

  # frontend:
  #   # Descomenta las líneas de para usar imagen de Docker Hub:
  #   image: roldyoran/cubepath-shorturl-frontend:latest
  #   pull_policy: always

  #   # Construcción local (comenta esto en producción):
  #   #build:
  #   #  context: ./frontend
  #   #  dockerfile: Dockerfile

  #   env_file:
  #     - .env
  #   container_name: cbpt-front
  #   ports:
  #     - "5173:5173"
  #   restart: unless-stopped
  #   networks:
  #     - cbpt-net

volumes:
  postgres_data:

networks:
  cbpt-net:
    driver: bridge
